name: ml
channels:
  - conda-forge
dependencies:
    # Put as many dependencies as possible at top level
  - python=3.11
  - scikit-learn
  - pandas
  - graphviz
  - pydotplus
  - seaborn
  - IPython
#  - pip:
#      - Extend, if cannot be installed with anaconda